### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/vue-eleicoes-2018#17]
Setup CI to run lint before merging. Could be any CI service.

**Comment by JacksonIsaac** [comment]
Working on it

**Comment by JacksonIsaac** [comment]
I tried to find documentations online, but didn't find anything much. Although, I did find one for using eslint with Travis: https://stackoverflow.com/questions/44463450/using-eslint-with-travis-ci

Let me know if I am the correct path or not :)

**Comment by viniciuskneves** [comment]
@JacksonIsaac you could try those tutorials:
- https://circleci.com/docs/2.0/hello-world/
- https://docs.travis-ci.com/user/getting-started/

It shouldn't be a fancy build. Let's start it with the simpler way possible. I mean just setup it with lint and then we think about improvements and so on...
