### ISSUE TITLE
Listar governadores

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/vue-eleicoes-2018#2]
Listar os governadores do estado de SC, e se possível dos outros estados.

Utilizar o projeto no qual esse está baseado para obter as rotas necessárias.

**Comment by chgasparoto** [comment]
Vou brincar com esse cara, não manjo de Vue, só React

**Comment by viniciuskneves** [comment]
Tranquilo @chgasparoto manda bala e qualquer dúvida é só chamar! :smile:
