### ISSUE TITLE
Listar deputados federais

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/vue-eleicoes-2018#4]
Semelhante a https://github.com/viniciuskneves/vue-eleicoes-2018/issues/2 porém para deputados federais

**Comment by vini23hot** [comment]
Vou pegar essa issue!

**Comment by viniciuskneves** [comment]
@vini23hot só aconselho a dar uma olahda nesse PR antes: https://github.com/viniciuskneves/vue-eleicoes-2018/pull/7
Já que ele muda um pouco a estrutura do projeto e deve facilitar o desenvolvimento dos novos módulos!

**Comment by vini23hot** [comment]
@viniciuskneves vish... tinha acabado agora de fazer as mudanças com base no PR #8 pra funcionar normalmente

**Comment by viniciuskneves** [comment]
Pode mandar, o outro PR é de reestruturação, aí só adaptamos as features existentes nele.

**Comment by viniciuskneves** [comment]
Valeu @vini23hot \o/
