### ISSUE TITLE
API DOC 

### ISSUE THREAD

**Issue by mikejavier** [viniciuskneves/vue-eleicoes-2018#6]
Oi,

Sabe dizer onde encontro mais informações sobre a API que lista os candidatos ?
procurei não achei nd. Queria saber mais sobre os endpoint para poder extrair as informações.

**Comment by chgasparoto** [comment]
@mikejavier você chegou a ver esse arquivo [https://github.com/diogomoretti/eleicoes2018/blob/master/src/js/components/api.js](url)?

É do projeto onde o @viniciuskneves se baseou.

**Comment by mikejavier** [comment]
@chgasparoto não tinha visto. 

Atualizei meu PR modificando a API do projeto conforme esse exemplo.

Agora ficou mais fácil. 😄
